/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as _newsroomPublishTrendingRouteImport } from './routes/__newsroom/publish-trending'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _newsroomPublishTrendingRoute =
  _newsroomPublishTrendingRouteImport.update({
    id: '/__newsroom/publish-trending',
    path: '/publish-trending',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/publish-trending': typeof _newsroomPublishTrendingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/publish-trending': typeof _newsroomPublishTrendingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__newsroom/publish-trending': typeof _newsroomPublishTrendingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/publish-trending'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/publish-trending'
  id: '__root__' | '/' | '/__newsroom/publish-trending'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _newsroomPublishTrendingRoute: typeof _newsroomPublishTrendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__newsroom/publish-trending': {
      id: '/__newsroom/publish-trending'
      path: '/publish-trending'
      fullPath: '/publish-trending'
      preLoaderRoute: typeof _newsroomPublishTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _newsroomPublishTrendingRoute: _newsroomPublishTrendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
